import {db} from "../firebase-config.js";import {collection,getDocs,query,where} from "https://www.gstatic.com/firebasejs/12.14.0/firebase-firestore.js";
const slug=new URLSearchParams(location.search).get("show")||"";const defaults={"on-the-walk":["On the Walk","Street conversations and reflections from SpeakOut."],"on-the-move":["SpeakOut On The Move","Real conversations with people where they are."],"podcast":["SpeakOut Podcast","Long-form conversations with guests and professionals."],"how-are-you-really":["How Are You, Really?","Short, human conversations about mental wellbeing."],"youth-voices":["Youth Voices","A platform for young people to discuss what affects them."],"campus-connect":["Campus Connect","Stories and conversations from schools and campuses."],"expert-corner":["Expert Corner","Informed educational conversations with qualified guests."],"speakout-stories":["SpeakOut Stories","Human and community stories that deserve to be heard."],"speakout-special":["SpeakOut Special","Events, campaigns and special coverage."]};
const starterEpisodes=[
{id:"archive-speakout-anthem",title:"SpeakOut Anthem | Together We Rise for Mental Health",show:"SpeakOut Special",description:"SpeakOut anthem and movement video.",url:"https://www.youtube.com/watch?v=tAoGJvkvNRg"},
{id:"archive-adhd-men",title:"Dear Men With ADHD: This Is For You | Spoken Word",show:"SpeakOut Stories",description:"A spoken-word conversation from SpeakOut.",url:"https://www.youtube.com/watch?v=ixDjSGFBA5Q"},
{id:"archive-religion",title:"This Might Change How You See Religion Forever",show:"SpeakOut Stories",description:"A SpeakOut conversation from our video archive.",url:"https://www.youtube.com/watch?v=PSq-nwyzrNk"},
{id:"archive-tired-nation",title:"Heavy Heart of a Tired Nation (Nigeria as a Case Study)",show:"SpeakOut Stories",description:"A SpeakOut reflection from our video archive.",url:"https://www.youtube.com/watch?v=EFOEWzO1a3E"},
{id:"archive-marital-decay",title:"The Silent Architect of Marital Decay",show:"SpeakOut Stories",description:"A SpeakOut conversation from our video archive.",url:"https://www.youtube.com/watch?v=akWDTQmn9K0"}
];
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));const norm=s=>String(s||"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
let meta=defaults[slug]||[slug.replace(/-/g," ").replace(/\b\w/g,c=>c.toUpperCase()),"SpeakOut TV original programming."];
try{const ss=await getDocs(query(collection(db,"tvShows"),where("status","in",["active","published"])));ss.forEach(d=>{const x=d.data();if((x.slug||norm(x.title))===slug){meta=[x.title||meta[0],x.description||meta[1]];document.getElementById("showHost").textContent=x.host?"Hosted by "+x.host:"";}})}catch{}
document.getElementById("showTitle").textContent=meta[0];document.getElementById("showDescription").textContent=meta[1];document.title=meta[0]+" | SpeakOut TV";
try{const s=await getDocs(query(collection(db,"tvEpisodes"),where("status","in",["active","published"])));const a=[];s.forEach(d=>{const x={id:d.id,...d.data()};if(norm(x.show)===slug)a.push(x)});const ids=new Set(a.map(x=>x.id));starterEpisodes.forEach(x=>{if(norm(x.show)===slug&&!ids.has(x.id))a.push(x)});document.getElementById("episodeGrid").innerHTML=a.length?a.map(x=>{let y="";try{const u=new URL(x.url||x.videoUrl);y=u.hostname==="youtu.be"?u.pathname.slice(1):u.searchParams.get("v")||u.pathname.match(/\/(?:live|shorts|embed)\/([^/?]+)/)?.[1]||""}catch{}const img=x.imageUrl||x.thumbnailUrl||(y?"https://i.ytimg.com/vi/"+encodeURIComponent(y)+"/hqdefault.jpg":"");return '<a class="card" href="'+(x.id.startsWith("archive-")?"tv.html?episode="+encodeURIComponent(x.id)+"#episodes":"watch.html?id="+encodeURIComponent(x.id))+'">'+(img?'<img class="episode-thumb" src="'+esc(img)+'" alt="" loading="lazy">':'<div class="thumb">'+esc(x.show||"SPEAKOUT TV")+'</div>')+'<div class="card-body"><small>'+esc(x.presenter?"HOST · "+x.presenter:x.show||"EPISODE")+'</small><h3>'+esc(x.title)+'</h3><p>'+esc(x.description||"")+'</p></div></a>'}).join(""):'<p class="empty-note">No published episodes yet.</p>'}catch{document.getElementById("episodeGrid").innerHTML='<p class="empty-note">No published episodes yet.</p>'}